
[project]
name = "mvp-shared"
description = "Shared development, docs and testing tools for the django-mvp org"
license = "MIT"
dynamic = ["version"]
readme = "README.md"
authors = [{ name = "Sam", email = "samuel.scott.jennings@gmail.com" }]
requires-python = '>=3.12,<4'
dependencies = []

[project.optional-dependencies]
test = [
    "coverage (>=7.15.4,<8.0.0)",
    "django-coverage-plugin (>=3.2.2,<4.0.0)",
    "pytest (>=9.1.1,<10.0.0)",
    "pytest-cov (>=7.1.0,<8.0.0)",
    "pytest-django (>=4.14.0,<5.0.0)",
    "pytest-env (>=1.7.0,<2.0.0)",
    "pytest-playwright (>=0.9.0,<0.10.0)",
    "pytest-sugar (>=1.1.1,<2.0.0)",
    "factory-boy (>=3.3.3,<4.0.0)",
    "beautifulsoup4 (>=4.15.0,<5.0.0)",
]
dev = [
    "deptry (>=0.25.1,<0.26.0)",
    "django-debug-toolbar (>=6.3.0,<7.0.0)",
    "django-debug-toolbar-template-profiler (>=2.1.0,<3.0.0)",
    "django-extensions (>=4.1,<5.0)",
    "django-stubs (>=6.1.0,<7.0.0)",
    "djlint (>=1.44.2,<2.0.0)",
    "invoke (>=3.0.3,<4.0.0)",
    "ipython (>=9.17.0,<10.0.0)",
    "mypy (>=2.3.1,<3.0.0)",
    "pre-commit (>=4.6.2,<5.0.0)",
    "types-python-dateutil (>=2.9.0.20260807,<3.0.0.0)",
    "types-requests (>=2.33.0.20260712,<3.0.0.0)",
    "djangorestframework-stubs (>=3.18.1,<4.0.0)",
    "django-model-info (>=2026.3.1,<2027.0.0)",
    "django-browser-reload (>=1.21.0,<2.0.0)",
    "ruff (>=0.15.22,<0.16.0)",
    "django-watchfiles (>=1.4.0,<2.0.0)",
]


[tool.poetry]
version = "0.4.0"
include = ["LICENSE", "README.md"]
requires-poetry = '>=2.0,<3.0'
packages = [{ include = "mvp_shared" }]

[build-system]
requires = ['poetry-core (>=2.0,<3.0)']
build-backend = "poetry.core.masonry.api"
