name: Deploy Docs

on:
  workflow_call:
    inputs:
      python-version:
        description: 'Python version to use'
        type: string
        default: '3.13'

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Set up Poetry env
        uses: SamuelJennings/cached-poetry-action@v2.0
        with:
          python-version: ${{ inputs.python-version }}

      - name: Configure Pages
        uses: actions/configure-pages@v5

      - name: Build documentation
        run: poetry run invoke docs

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v4
        with:
          path: ./docs

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
